plugins {
    id("idea")
    id("eclipse")
    id("maven-publish")
    id("net.kyori.blossom") version "2.1.0" // https://github.com/KyoriPowered/blossom
    id("dev.ithundxr.silk") version "1.0.1" // https://github.com/ithundxr/silk
    id("net.neoforged.moddev") version "2.0.107" // https://projects.neoforged.net/neoforged/ModDevGradle
    id("me.modmuss50.mod-publish-plugin") version "0.8.4" // https://github.com/modmuss50/mod-publish-plugin
    id("org.jetbrains.gradle.plugin.idea-ext") version "1.1.8" // https://github.com/JetBrains/gradle-idea-ext-plugin
}

idea {
    module {
        //Exclude directories from being managed
        for (String excludeDirName in ["runs", "out", "logs", "gradle"]) {
            excludeDirs.add(file(excludeDirName))
        }
        //Tell IDEA to always download sources/javadoc artifacts from maven.
        downloadJavadoc = true
        downloadSources = true
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

base {
    version = minecraft_version + '-' + create_version + '-' + mod_version
    group = mod_author + '.' + mod_id // http://maven.apache.org/guides/mini/guide-naming-conventions.html
    archivesName = mod_id + "-neoforge"
}

neoForge {
    version = project.neo_version

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    parchment {
        mappingsVersion = project.parchment_version
        minecraftVersion = project.parchment_minecraft_version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {
            systemProperty 'mixin.debug.verbose', 'true'
            systemProperty 'mixin.debug.export', 'true'
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }
}

sourceSets.main.resources {
    srcDirs += 'src/generated/resources'
    exclude '.cache'
}


configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    //maven { url = "https://mvn.devos.one/snapshots" } // Registrate
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
    maven { url = "https://maven.createmod.net" } // Ponder, Flywheel
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // NeoForge config api port, needed by ponder
    maven { url = "https://maven.blamejared.com" } // JEI, Vazkii's Mods
    maven { url = "https://maven.theillusivec4.top/" } // Curios API
    maven { url = "https://www.cursemaven.com" }
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.architectury.dev" } // Arch API
    maven {
        url "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }
    maven {
        name 'JitPack'
        url 'https://jitpack.io'
        content {
            includeGroupByRegex '(io|com)\\.github\\..*'
        }
    }

}
dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
    implementation("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}-${create_version_suffix}:slim") { transitive = false }

    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    compileOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}:api")
    runtimeOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}")

    // Farmer's Delight
    compileOnly("curse.maven:farmers-delight-398521:${farmersdelight_version}")
    runtimeOnly("curse.maven:farmers-delight-398521:${farmersdelight_version}")

    // Create's Crafts & Additions
    compileOnly("curse.maven:createaddition-439890:${createaddition_Version}")
    runtimeOnly("curse.maven:createaddition-439890:${createaddition_Version}")

    // Jade
    compileOnly("curse.maven:jade-324717:${jade_neoforge_id}")
    runtimeOnly("curse.maven:jade-324717:${jade_neoforge_id}")

    // The One Probe
    compileOnly("curse.maven:the-one-probe-245211:${top_neoforge_id}")
    runtimeOnly("curse.maven:the-one-probe-245211:${top_neoforge_id}")

    implementation("dev.latvian.mods:kubejs-create-neoforge:${kubejs_create_version}")
    api("dev.latvian.mods:kubejs-neoforge:$kubejs_version")
    interfaceInjectionData("dev.latvian.mods:kubejs-neoforge:$kubejs_version")

}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            neo_version            : neo_version,
            create_version_range   : create_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_long_version       : minecraft_version + "-" + create_version  + "-" + mod_version,
            mod_author             : mod_author,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : mod_id,
                "Specification-Vendor"    : mod_author,
                "Specification-Version"   : mod_version,
                "Implementation-Title"    : project.jar.archiveBaseName,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : mod_author,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs": "createlowheated.mixins.json"
        ])
    }
}

compileJava {
    options.compilerArgs = ['-Xdiags:verbose']
}
