plugins {
    id("idea")
    id("eclipse")
    id("maven-publish")
    id("net.kyori.blossom") version "2.1.0" // https://github.com/KyoriPowered/blossom
    id("dev.ithundxr.silk") version "0.11.15" // https://github.com/ithundxr/silk
    id("me.modmuss50.mod-publish-plugin") version "0.8.4" // https://github.com/modmuss50/mod-publish-plugin
    id("net.neoforged.moddev.legacyforge") version "2.0.107" // https://projects.neoforged.net/neoforged/ModDevGradle
    id("org.jetbrains.gradle.plugin.idea-ext") version "1.1.8" // https://github.com/JetBrains/gradle-idea-ext-plugin
}

apply(from: "./gradle/java.gradle")
//apply(from: "gradle/property_loader.gradle")

base {
    group = mod_author + '.' + mod_id
    archivesBaseName = mod_id + "-forge"
    version = minecraft_version + '-' + create_version + '-' + mod_version
}

Provider<RegularFile> refmap
mixin {
    refmap = add(sourceSets.main, "createlowheated.refmap.json")
    config "createlowheated.mixins.json"
}

println("Java: ${System.getProperty("java.version")}, JVM: ${System.getProperty("java.vm.version")} (${System.getProperty("java.vendor")}), Arch: ${System.getProperty("os.arch")}")

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

legacyForge {
    version = "$minecraft_version-$forge_version"

    // TODO - Try turning this on later
    validateAccessTransformers = false

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }

    mods {
        create {
            sourceSet(sourceSets.main)
        }

    }

    runs {
        configureEach {
            systemProperty("forge.logging.markers", "")
            systemProperty("forge.logging.console.level", "info")
            jvmArguments = ["-XX:+IgnoreUnrecognizedVMOptions", "-XX:+AllowEnhancedClassRedefinition"]

            systemProperty("mixin.debug.export", "true")
            systemProperty("mixin.debug.verbose", "true")

            programArgument('-mixin.config=createlowheated.mixins.json')
        }

        client {
            client()
            gameDirectory = project.file("run")
        }

        server {
            server()

            gameDirectory = project.file("run/server")
        }

        data {
            data()
            gameDirectory = project.file("run")
            systemProperty("forge.logging.markers", "REGISTRIES,REGISTRYDUMP")
            systemProperty("forge.logging.console.level", "debug")

            programArguments.addAll(
                    "--mod", mod_id as String,
                    "--all",
                    "--output", file("src/generated/resources/").getAbsolutePath(),
                    "--existing", file("src/main/resources").getAbsolutePath(),
                    '--existing-mod', 'create'
            )
        }

        gameTestServer {
            type = "gameTestServer"
            gameDirectory = project.file("run/gametest")
        }
    }
}

repositories {
    maven { url = "https://maven.createmod.net" } // Ponder, Flywheel
    maven { url = "https://maven.ithundxr.dev/mirror" } // Registrate
    maven { url = "https://maven.blamejared.com" } // JEI, Vazkii's Mods
    maven { url = "https://www.cursemaven.com" }
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.architectury.dev" } // Arch API
    maven {
        url "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
        }
    }

    flatDir {
        dirs 'libs'
    }
}

dependencies {
    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")

    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}-${create_version_suffix}:slim") { transitive = false }

    //compileOnly fg.deobf("mezz.jei:jei-${jei_minecraft_version}-common-api:${jei_version}")
    //compileOnly fg.deobf("mezz.jei:jei-${jei_minecraft_version}-forge-api:${jei_version}")
    //runtimeOnly fg.deobf("mezz.jei:jei-${jei_minecraft_version}-forge:${jei_version}")
    modImplementation("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    modImplementation("dev.latvian.mods:kubejs-create-forge:${kubejs_create_version}")
    modImplementation("dev.latvian.mods:kubejs-forge:${kubejs_version}")
    modImplementation("dev.architectury:architectury-forge:${architectury_version}")
    modImplementation("dev.latvian.mods:rhino-forge:${rhino_version}")

    // Create's Crafts & Additions
    modCompileOnly("curse.maven:createaddition-439890:${createaddition_version}")
    modRuntimeOnly("curse.maven:createaddition-439890:${createaddition_version}")

    if (!Boolean.getBoolean("idea.sync.active")) {
        annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude '.cache/'
}

processResources {
    var replaceProperties = [
            mod_id         : mod_id,
            mod_name       : mod_name,
            mod_author     : mod_author,
            mod_description: mod_description,
            mod_license    : mod_license,
    ]

    // Replaces FML's magic file.jarVersion string with the correct version at build time.
    replaceProperties.put("file", [jarVersion: project.version])

    filesMatching(["META-INF/mods.toml"]) {
        expand(replaceProperties)
    }
}

jar {
    String name = base.archivesName.get()

    from("LICENSE") {
        rename { "${it}_${name}" }
    }

    manifest.attributes([
            "MixinConfigs": "createlowheated.mixins.json"
    ])
}

/*
jar {
    manifest {
        attributes([
                "Specification-Title"     : mod_id,
                "Specification-Vendor"    : mod_author,
                "Specification-Version"   : "1", // We are version 1 of ourselves
                'Implementation-Title'    : project.jar.archiveBaseName,
                'Implementation-Version'  : project.jar.archiveVersion,
                "Implementation-Vendor"   : mod_author,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ", TimeZone.getTimeZone("UTC")),
                "MixinConfigs"            : "createlowheated.mixins.json"
        ])
    }
}

// Example configuration to allow publishing using the maven-publish plugin
// This is the preferred method to reobfuscate your jar file
jar.finalizedBy('reobfJar')
*/