org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Project
mod_id=createlowheated
mod_author=zeh
mod_version=2

minecraft_version = 1.20.1
forge_version = 47.2.6

# build dependency versions
forgegradle_version = 6.0.6
mixingradle_version = 0.7-SNAPSHOT
mixin_version = 0.8.5
librarian_version = 1.+
cursegradle_version = 1.4.0

parchment_version = 2023.09.03
use_parchment = true

# dependency versions

registrate_version = MC1.20-1.3.3

flywheel_minecraft_version = 1.20.1
flywheel_version = 1.0.1

ponder_minecraft_version = 1.20.1
ponder_version = 1.0.51

create_minecraft_version = 1.20.1
create_version = 6.0.2
create_version_suffix = 53

jei_minecraft_version = 1.20.1
jei_version = 15.19.5.99

kubejs_version=2001.6.4-build.114
kubejs_create_version=2001.2.5-build.2
rhino_version=2001.2.2-build.+
architectury_version=9.1.12
