modLoader="javafml"
# The loader version doesn't matter. Modify the NeoForge and/or Minecraft version ranges instead.
loaderVersion = "[0,)"
license="MIT"
issueTrackerURL="https://github.com/zehmaria/createlowheated/issues"
displayURL="https://github.com/zehmaria/createlowheated"

[[mods]]
modId="${mod_id}"
version="${mod_long_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${mod_author}"
description="${mod_description}"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange = "[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs_create"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange = "[${minecraft_version}]"
ordering="NONE"
side="BOTH"
